import 'dart:async';

import 'package:hive_ce/hive.dart';
import 'package:kache/kache.dart';

import 'package:mikan/core/models/bangumi.dart';
import 'package:mikan/core/models/bangumi_details.dart';
import 'package:mikan/core/models/bangumi_row.dart';
import 'package:mikan/core/models/fonts.dart';
import 'package:mikan/core/models/record_details.dart';
import 'package:mikan/core/models/record_item.dart';
import 'package:mikan/core/models/season.dart' as model;
import 'package:mikan/core/models/season_data.dart';
import 'package:mikan/core/models/season_gallery.dart';
import 'package:mikan/core/models/search.dart';
import 'package:mikan/core/models/subgroup.dart';
import 'package:mikan/core/models/subgroup_bangumi.dart';

/// TypeIds for hand-written adapters that are NOT generated by hive_ce_generator.
///
/// Values 2-12 are already used by generated adapters (see [MyHive]); we use
/// 100+ to avoid any collision with future codegen output.
const int _typeIdRecordDetail = 100;
const int _typeIdSeasonGallery = 101;
const int _typeIdSeasonData = 102;
const int _typeIdSubgroupBangumi = 103;
const int _typeIdBangumiDetail = 104;
const int _typeIdSearchResult = 105;
const int _typeIdFont = 106;
const int _typeIdLicense = 107;

/// Registers the hand-written [TypeAdapter]s needed by the Kache persistence
/// layer for models that are not annotated with `@HiveType`.
///
/// Must be called once after [Hive.registerAdapters] and before any
/// [HiveKacheStore] read/write that involves these types.
void registerKacheAdapters(HiveInterface hive) {
  if (!hive.isAdapterRegistered(_typeIdRecordDetail)) {
    hive.registerAdapter(RecordDetailAdapter());
  }
  if (!hive.isAdapterRegistered(_typeIdSeasonGallery)) {
    hive.registerAdapter(SeasonGalleryAdapter());
  }
  if (!hive.isAdapterRegistered(_typeIdSeasonData)) {
    hive.registerAdapter(SeasonDataAdapter());
  }
  if (!hive.isAdapterRegistered(_typeIdSubgroupBangumi)) {
    hive.registerAdapter(SubgroupBangumiAdapter());
  }
  if (!hive.isAdapterRegistered(_typeIdBangumiDetail)) {
    hive.registerAdapter(BangumiDetailAdapter());
  }
  if (!hive.isAdapterRegistered(_typeIdSearchResult)) {
    hive.registerAdapter(SearchResultAdapter());
  }
  if (!hive.isAdapterRegistered(_typeIdLicense)) {
    hive.registerAdapter(LicenseAdapter());
  }
  if (!hive.isAdapterRegistered(_typeIdFont)) {
    hive.registerAdapter(FontAdapter());
  }
}

/// A [KachePersistenceBackend] backed by a Hive CE [Box].
///
/// Unlike [HiveCeKacheStore] (which writes versioned byte envelopes and
/// requires per-model codecs), this store writes **typed values directly** into
/// the Hive box. This reuses every already-registered [TypeAdapter] —
/// generated or hand-written — with zero serialization boilerplate.
///
/// Each entry is stored as a [_StoredEntry] record containing the typed data
/// and its metadata (fetchedAt, isInvalidated). Hive's own adapter mechanism
/// handles serialization to disk.
final class HiveKacheStore implements KachePersistenceBackend {
  HiveKacheStore._(this._box, this._owned);

  final Box<_StoredEntry> _box;
  final bool _owned;
  bool _isClosed = false;

  /// Opens a Hive box named [boxName] for Kache persistence.
  ///
  /// All model [TypeAdapter]s must be registered with [Hive] before calling
  /// this, including the [_StoredEntryAdapter] and any custom adapters from
  /// [registerKacheAdapters].
  static Future<HiveKacheStore> open({required String boxName}) async {
    if (!Hive.isAdapterRegistered(_typeIdStoredEntry)) {
      Hive.registerAdapter(_StoredEntryAdapter());
    }
    final box = await Hive.openBox<_StoredEntry>(boxName);
    return HiveKacheStore._(box, true);
  }

  @override
  Future<KachePersistenceRead<T>?> read<T>({
    required KacheKey key,
    required KachePersistenceBinding<T> binding,
  }) async {
    _ensureOpen();
    binding.ensureBackend(this);
    final raw = _box.get(key.storageKey);
    if (raw == null) {
      return null;
    }
    final entry = _StoredEntry.fromBox(raw);
    return KachePersistenceRead<T>(
      entry: KachePersistedEntry<T>(
        data: entry.data as T,
        metadata: KachePersistedMetadata(
          fetchedAt: entry.fetchedAt,
          isInvalidated: entry.isInvalidated,
        ),
      ),
    );
  }

  @override
  Future<void> write<T>({
    required KacheKey key,
    required KachePersistenceBinding<T> binding,
    required KachePersistedEntry<T> entry,
  }) async {
    _ensureOpen();
    binding.ensureBackend(this);
    final stored = _StoredEntry(
      data: entry.data,
      fetchedAt: entry.metadata.fetchedAt,
      isInvalidated: entry.metadata.isInvalidated,
    );
    await _box.put(key.storageKey, stored);
  }

  @override
  Future<void> delete({required KacheKey key}) async {
    _ensureOpen();
    await _box.delete(key.storageKey);
  }

  @override
  Future<void> clearNamespace({required KacheNamespace namespace}) async {
    _ensureOpen();
    final prefix = namespace.storagePrefix;
    final keys = _box.keys.whereType<String>().where((k) => k.startsWith(prefix)).toList();
    await _box.deleteAll(keys);
  }

  @override
  Future<void> clear() async {
    _ensureOpen();
    await _box.clear();
  }

  @override
  Future<void> close() async {
    if (_isClosed) {
      return;
    }
    _isClosed = true;
    if (_owned) {
      await _box.close();
    }
  }

  void _ensureOpen() {
    if (_isClosed) {
      throw StateError('HiveKacheStore is closed.');
    }
  }
}

/// A persistable wrapper that stores the typed data alongside Kache metadata.
///
/// The [data] field can hold any type with a registered Hive [TypeAdapter].
class _StoredEntry {
  _StoredEntry({required this.data, required this.fetchedAt, required this.isInvalidated});

  factory _StoredEntry.fromBox(_StoredEntry other) => other;

  final dynamic data;
  final DateTime fetchedAt;
  final bool isInvalidated;
}

const int _typeIdStoredEntry = 200;

class _StoredEntryAdapter extends TypeAdapter<_StoredEntry> {
  @override
  final int typeId = _typeIdStoredEntry;

  @override
  _StoredEntry read(BinaryReader reader) {
    final numFields = reader.readByte();
    dynamic data;
    DateTime fetchedAt = DateTime.fromMillisecondsSinceEpoch(0);
    bool isInvalidated = false;
    for (var i = 0; i < numFields; i++) {
      switch (reader.readByte()) {
        case 0:
          data = reader.read();
        case 1:
          fetchedAt = reader.read() as DateTime;
        case 2:
          isInvalidated = reader.readBool();
      }
    }
    return _StoredEntry(data: data, fetchedAt: fetchedAt, isInvalidated: isInvalidated);
  }

  @override
  void write(BinaryWriter writer, _StoredEntry obj) {
    writer
      ..writeByte(3)
      ..writeByte(0)
      ..write(obj.data)
      ..writeByte(1)
      ..write(obj.fetchedAt)
      ..writeByte(2)
      ..writeBool(obj.isInvalidated);
  }
}

// ---------------------------------------------------------------------------
// Hand-written TypeAdapters for non-@HiveType models
// ---------------------------------------------------------------------------

/// Serializes [RecordDetail]. The computed `share` field is excluded — it is
/// re-derived lazily on read via its `late final` initializer.
class RecordDetailAdapter extends TypeAdapter<RecordDetail> {
  @override
  final int typeId = _typeIdRecordDetail;

  @override
  RecordDetail read(BinaryReader reader) {
    final detail = RecordDetail();
    final numFields = reader.readByte();
    for (var i = 0; i < numFields; i++) {
      switch (reader.readByte()) {
        case 0:
          detail.id = reader.read() as String?;
        case 1:
          detail.cover = reader.readString();
        case 2:
          detail.name = reader.readString();
        case 3:
          detail.subscribed = reader.readBool();
        case 4:
          detail.more = (reader.read() as Map).cast<String, String>();
        case 5:
          detail.intro = reader.readString();
        case 6:
          detail.subgroups = (reader.read() as List).cast<Subgroup>();
        case 7:
          detail.url = reader.readString();
        case 8:
          detail.title = reader.readString();
        case 9:
          detail.magnet = reader.readString();
        case 10:
          detail.torrent = reader.readString();
        case 11:
          detail.tags = (reader.read() as List).cast<String>();
      }
    }
    return detail;
  }

  @override
  void write(BinaryWriter writer, RecordDetail obj) {
    writer
      ..writeByte(12)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..writeString(obj.cover)
      ..writeByte(2)
      ..writeString(obj.name)
      ..writeByte(3)
      ..writeBool(obj.subscribed)
      ..writeByte(4)
      ..writeMap(obj.more)
      ..writeByte(5)
      ..writeString(obj.intro)
      ..writeByte(6)
      ..writeList(obj.subgroups)
      ..writeByte(7)
      ..writeString(obj.url)
      ..writeByte(8)
      ..writeString(obj.title)
      ..writeByte(9)
      ..writeString(obj.magnet)
      ..writeByte(10)
      ..writeString(obj.torrent)
      ..writeByte(11)
      ..writeList(obj.tags);
  }
}

/// Serializes [SeasonGallery].
class SeasonGalleryAdapter extends TypeAdapter<SeasonGallery> {
  @override
  final int typeId = _typeIdSeasonGallery;

  @override
  SeasonGallery read(BinaryReader reader) {
    final gallery = SeasonGallery.empty();
    final numFields = reader.readByte();
    for (var i = 0; i < numFields; i++) {
      switch (reader.readByte()) {
        case 0:
          gallery.year = reader.readString();
        case 1:
          gallery.season = reader.readString();
        case 2:
          gallery.title = reader.readString();
        case 3:
          gallery.active = reader.readBool();
        case 4:
          gallery.bangumis = (reader.read() as List).cast<Bangumi>();
      }
    }
    return gallery;
  }

  @override
  void write(BinaryWriter writer, SeasonGallery obj) {
    writer
      ..writeByte(5)
      ..writeByte(0)
      ..writeString(obj.year)
      ..writeByte(1)
      ..writeString(obj.season)
      ..writeByte(2)
      ..writeString(obj.title)
      ..writeByte(3)
      ..writeBool(obj.active)
      ..writeByte(4)
      ..writeList(obj.bangumis);
  }
}

/// Serializes [SeasonData]. This is a simple wrapper around [model.Season] and
/// `List<BangumiRow>`, both of which already have registered adapters.
class SeasonDataAdapter extends TypeAdapter<SeasonData> {
  @override
  final int typeId = _typeIdSeasonData;

  @override
  SeasonData read(BinaryReader reader) {
    final numFields = reader.readByte();
    model.Season? season;
    List<BangumiRow> bangumiRows = const [];
    for (var i = 0; i < numFields; i++) {
      switch (reader.readByte()) {
        case 0:
          season = reader.read() as model.Season;
        case 1:
          bangumiRows = (reader.read() as List).cast<BangumiRow>();
      }
    }
    return SeasonData(season: season!, bangumiRows: bangumiRows);
  }

  @override
  void write(BinaryWriter writer, SeasonData obj) {
    writer
      ..writeByte(2)
      ..writeByte(0)
      ..write(obj.season)
      ..writeByte(1)
      ..writeList(obj.bangumiRows);
  }
}

/// Serializes [SubgroupBangumi].
class SubgroupBangumiAdapter extends TypeAdapter<SubgroupBangumi> {
  @override
  final int typeId = _typeIdSubgroupBangumi;

  @override
  SubgroupBangumi read(BinaryReader reader) {
    final obj = SubgroupBangumi();
    final numFields = reader.readByte();
    for (var i = 0; i < numFields; i++) {
      switch (reader.readByte()) {
        case 0:
          obj.name = reader.readString();
        case 1:
          obj.dataId = reader.readString();
        case 2:
          obj.subgroups = (reader.read() as List).cast<Subgroup>();
        case 3:
          obj.subscribed = reader.readBool();
        case 4:
          obj.sublang = reader.read() as String?;
        case 5:
          obj.rss = reader.read() as String?;
        case 6:
          obj.state = reader.readInt();
        case 7:
          obj.records = (reader.read() as List).cast<RecordItem>();
      }
    }
    return obj;
  }

  @override
  void write(BinaryWriter writer, SubgroupBangumi obj) {
    writer
      ..writeByte(8)
      ..writeByte(0)
      ..writeString(obj.name)
      ..writeByte(1)
      ..writeString(obj.dataId)
      ..writeByte(2)
      ..writeList(obj.subgroups)
      ..writeByte(3)
      ..writeBool(obj.subscribed)
      ..writeByte(4)
      ..write(obj.sublang)
      ..writeByte(5)
      ..write(obj.rss)
      ..writeByte(6)
      ..writeInt(obj.state)
      ..writeByte(7)
      ..writeList(obj.records);
  }
}

/// Serializes [BangumiDetail]. The computed `share` field is excluded — it is
/// re-derived lazily on read via its `late final` initializer.
class BangumiDetailAdapter extends TypeAdapter<BangumiDetail> {
  @override
  final int typeId = _typeIdBangumiDetail;

  @override
  BangumiDetail read(BinaryReader reader) {
    final obj = BangumiDetail();
    final numFields = reader.readByte();
    for (var i = 0; i < numFields; i++) {
      switch (reader.readByte()) {
        case 0:
          obj.id = reader.readString();
        case 1:
          obj.cover = reader.readString();
        case 2:
          obj.name = reader.readString();
        case 3:
          obj.subscribed = reader.readBool();
        case 4:
          obj.more = (reader.read() as Map).cast<String, String>();
        case 5:
          obj.intro = reader.readString();
        case 6:
          obj.subgroupBangumis =
              (reader.read() as Map).cast<String, SubgroupBangumi>();
      }
    }
    return obj;
  }

  @override
  void write(BinaryWriter writer, BangumiDetail obj) {
    writer
      ..writeByte(7)
      ..writeByte(0)
      ..writeString(obj.id)
      ..writeByte(1)
      ..writeString(obj.cover)
      ..writeByte(2)
      ..writeString(obj.name)
      ..writeByte(3)
      ..writeBool(obj.subscribed)
      ..writeByte(4)
      ..writeMap(obj.more)
      ..writeByte(5)
      ..writeString(obj.intro)
      ..writeByte(6)
      ..writeMap(obj.subgroupBangumis);
  }
}

/// Serializes [SearchResult].
class SearchResultAdapter extends TypeAdapter<SearchResult> {
  @override
  final int typeId = _typeIdSearchResult;

  @override
  SearchResult read(BinaryReader reader) {
    List<Bangumi> bangumis = const [];
    List<Subgroup> subgroups = const [];
    List<RecordItem> records = const [];
    final numFields = reader.readByte();
    for (var i = 0; i < numFields; i++) {
      switch (reader.readByte()) {
        case 0:
          bangumis = (reader.read() as List).cast<Bangumi>();
        case 1:
          subgroups = (reader.read() as List).cast<Subgroup>();
        case 2:
          records = (reader.read() as List).cast<RecordItem>();
      }
    }
    return SearchResult(bangumis: bangumis, subgroups: subgroups, records: records);
  }

  @override
  void write(BinaryWriter writer, SearchResult obj) {
    writer
      ..writeByte(3)
      ..writeByte(0)
      ..writeList(obj.bangumis)
      ..writeByte(1)
      ..writeList(obj.subgroups)
      ..writeByte(2)
      ..writeList(obj.records);
  }
}

/// Serializes [License].
class LicenseAdapter extends TypeAdapter<License> {
  @override
  final int typeId = _typeIdLicense;

  @override
  License read(BinaryReader reader) {
    return License(
      name: reader.readString(),
      url: reader.readString(),
    );
  }

  @override
  void write(BinaryWriter writer, License obj) {
    writer
      ..writeString(obj.name)
      ..writeString(obj.url);
  }
}

/// Serializes [Font].
class FontAdapter extends TypeAdapter<Font> {
  @override
  final int typeId = _typeIdFont;

  @override
  Font read(BinaryReader reader) {
    final numFields = reader.readByte();
    String id = '';
    String name = '';
    List<String> files = const [];
    String desc = '';
    String official = '';
    License license = License(name: '', url: '');
    for (var i = 0; i < numFields; i++) {
      switch (reader.readByte()) {
        case 0:
          id = reader.readString();
        case 1:
          name = reader.readString();
        case 2:
          files = reader.readStringList();
        case 3:
          desc = reader.readString();
        case 4:
          official = reader.readString();
        case 5:
          license = reader.read() as License;
      }
    }
    return Font(
      id: id,
      name: name,
      files: files,
      desc: desc,
      official: official,
      license: license,
    );
  }

  @override
  void write(BinaryWriter writer, Font obj) {
    writer
      ..writeByte(6)
      ..writeByte(0)
      ..writeString(obj.id)
      ..writeByte(1)
      ..writeString(obj.name)
      ..writeByte(2)
      ..writeStringList(obj.files)
      ..writeByte(3)
      ..writeString(obj.desc)
      ..writeByte(4)
      ..writeString(obj.official)
      ..writeByte(5)
      ..write(obj.license);
  }
}
