// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMzd4rsfJFASIMtSzGguazInv7AN-87ns',
    appId: '1:626809778849:android:7edb4cb082be9274edb6e0',
    messagingSenderId: '626809778849',
    projectId: 'flutter-mikan',
    databaseURL: 'https://flutter-mikan.firebaseio.com',
    storageBucket: 'flutter-mikan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPj6xwYmdFGuCUHeSEt6mD4AjGw-_M1kM',
    appId: '1:626809778849:ios:d580f4b3810bebb7edb6e0',
    messagingSenderId: '626809778849',
    projectId: 'flutter-mikan',
    databaseURL: 'https://flutter-mikan.firebaseio.com',
    storageBucket: 'flutter-mikan.appspot.com',
    androidClientId: '626809778849-j0s442pnv7vs989f9jsnricrqpnu4llq.apps.googleusercontent.com',
    iosClientId: '626809778849-guglnjbelfb3scmjirffr0k09uh3kgkd.apps.googleusercontent.com',
    iosBundleId: 'io.nichijou.flutter.mikan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPj6xwYmdFGuCUHeSEt6mD4AjGw-_M1kM',
    appId: '1:626809778849:ios:d580f4b3810bebb7edb6e0',
    messagingSenderId: '626809778849',
    projectId: 'flutter-mikan',
    databaseURL: 'https://flutter-mikan.firebaseio.com',
    storageBucket: 'flutter-mikan.appspot.com',
    androidClientId: '626809778849-j0s442pnv7vs989f9jsnricrqpnu4llq.apps.googleusercontent.com',
    iosClientId: '626809778849-guglnjbelfb3scmjirffr0k09uh3kgkd.apps.googleusercontent.com',
    iosBundleId: 'io.nichijou.flutter.mikan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEugQDoRskx6U2coSgORsKbyJMUbSmDXE',
    appId: '1:626809778849:web:34c84189c94d1c57edb6e0',
    messagingSenderId: '626809778849',
    projectId: 'flutter-mikan',
    authDomain: 'flutter-mikan.firebaseapp.com',
    databaseURL: 'https://flutter-mikan.firebaseio.com',
    storageBucket: 'flutter-mikan.appspot.com',
    measurementId: 'G-WJKPHGHK7F',
  );
}
