// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mikan/core/models/announcement.dart';
import 'package:mikan/core/models/bangumi.dart';
import 'package:mikan/core/models/bangumi_details.dart';
import 'package:mikan/core/models/bangumi_row.dart';
import 'package:mikan/core/models/cached_list.dart';
import 'package:mikan/core/models/carousel.dart';
import 'package:mikan/core/models/fonts.dart';
import 'package:mikan/core/models/index.dart';
import 'package:mikan/core/models/record_details.dart';
import 'package:mikan/core/models/record_item.dart';
import 'package:mikan/core/models/search.dart';
import 'package:mikan/core/models/season.dart';
import 'package:mikan/core/models/season_data.dart';
import 'package:mikan/core/models/season_gallery.dart';
import 'package:mikan/core/models/subgroup.dart';
import 'package:mikan/core/models/subgroup_bangumi.dart';
import 'package:mikan/core/models/user.dart';
import 'package:mikan/core/models/year_season.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnnouncementAdapter());
    registerAdapter(AnnouncementNodeAdapter());
    registerAdapter(BangumiAdapter());
    registerAdapter(BangumiDetailAdapter());
    registerAdapter(BangumiRowAdapter());
    registerAdapter(CachedBangumiListAdapter());
    registerAdapter(CachedFontListAdapter());
    registerAdapter(CachedRecordListAdapter());
    registerAdapter(CachedSeasonGalleryListAdapter());
    registerAdapter(CarouselAdapter());
    registerAdapter(FontAdapter());
    registerAdapter(IndexAdapter());
    registerAdapter(LicenseAdapter());
    registerAdapter(RecordDetailAdapter());
    registerAdapter(RecordItemAdapter());
    registerAdapter(SearchResultAdapter());
    registerAdapter(SeasonAdapter());
    registerAdapter(SeasonDataAdapter());
    registerAdapter(SeasonGalleryAdapter());
    registerAdapter(SubgroupAdapter());
    registerAdapter(SubgroupBangumiAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(YearSeasonAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnnouncementAdapter());
    registerAdapter(AnnouncementNodeAdapter());
    registerAdapter(BangumiAdapter());
    registerAdapter(BangumiDetailAdapter());
    registerAdapter(BangumiRowAdapter());
    registerAdapter(CachedBangumiListAdapter());
    registerAdapter(CachedFontListAdapter());
    registerAdapter(CachedRecordListAdapter());
    registerAdapter(CachedSeasonGalleryListAdapter());
    registerAdapter(CarouselAdapter());
    registerAdapter(FontAdapter());
    registerAdapter(IndexAdapter());
    registerAdapter(LicenseAdapter());
    registerAdapter(RecordDetailAdapter());
    registerAdapter(RecordItemAdapter());
    registerAdapter(SearchResultAdapter());
    registerAdapter(SeasonAdapter());
    registerAdapter(SeasonDataAdapter());
    registerAdapter(SeasonGalleryAdapter());
    registerAdapter(SubgroupAdapter());
    registerAdapter(SubgroupBangumiAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(YearSeasonAdapter());
  }
}
