// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:ff_annotation_route/ff_annotation_route.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:mikan_flutter/model/record_item.dart';
import 'package:mikan_flutter/model/season_gallery.dart';
import 'package:mikan_flutter/model/subgroup.dart';
import 'package:mikan_flutter/model/year_season.dart';
import 'ui/pages/bangumi_page.dart';
import 'ui/pages/home_page.dart';
import 'ui/pages/login_page.dart';
import 'ui/pages/recent_subscribed_page.dart';
import 'ui/pages/record_detail_page.dart';
import 'ui/pages/season_list_page.dart';
import 'ui/pages/splash_page.dart';
import 'ui/pages/subgroup_page.dart';
import 'ui/pages/subscribed_season_page.dart';

RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  arguments = arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'bangumi':
      return RouteResult(
        name: name,
        widget: BangumiPage(
          key: arguments['key'] as Key,
          bangumiId: arguments['bangumiId'] as String,
          cover: arguments['cover'] as String,
          heroTag: arguments['heroTag'] as String,
        ),
        routeName: 'bangumi',
      );
    case 'home':
      return RouteResult(
        name: name,
        widget: HomePage(),
        routeName: 'home',
      );
    case 'login':
      return RouteResult(
        name: name,
        widget: LoginPage(),
        routeName: 'login',
      );
    case 'recent-subscribed':
      return RouteResult(
        name: name,
        widget: RecentSubscribedPage(
          key: arguments['key'] as Key,
          loaded: arguments['loaded'] as List<RecordItem>,
        ),
        routeName: 'recent-subscribed',
      );
    case 'record-detail':
      return RouteResult(
        name: name,
        widget: RecordDetailPage(
          key: arguments['key'] as Key,
          url: arguments['url'] as String,
        ),
        routeName: 'record-detail',
      );
    case 'season-list':
      return RouteResult(
        name: name,
        widget: SeasonListPage(
          key: arguments['key'] as Key,
          years: arguments['years'] as List<YearSeason>,
        ),
        routeName: 'season-list',
      );
    case 'splash':
      return RouteResult(
        name: name,
        widget: SplashPage(),
        routeName: 'splash',
      );
    case 'subgroup':
      return RouteResult(
        name: name,
        widget: SubgroupPage(
          key: arguments['key'] as Key,
          subgroup: arguments['subgroup'] as Subgroup,
        ),
        routeName: 'subgroup',
      );
    case 'subscribed-season':
      return RouteResult(
        name: name,
        widget: SubscribedSeasonPage(
          key: arguments['key'] as Key,
          years: arguments['years'] as List<YearSeason>,
          galleries: arguments['galleries'] as List<SeasonGallery>,
        ),
        routeName: 'subscribed-season',
      );
    default:
      return const RouteResult(name: 'flutterCandies://notfound');
  }
}

class RouteResult {
  const RouteResult({
    @required this.name,
    this.widget,
    this.showStatusBar = true,
    this.routeName = '',
    this.pageRouteType,
    this.description = '',
    this.exts,
  });

  /// The name of the route (e.g., "/settings").
  ///
  /// If null, the route is anonymous.
  final String name;

  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  /// The extend arguments
  final Map<String, dynamic> exts;
}
