// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
class Routes {
  const Routes._();

  /// 'bangumi-details'
  ///
  /// [name] : 'mikan://bangumi-details'
  ///
  /// [routeName] : 'bangumi-details'
  ///
  /// [arguments] : [title, url, name, cover]
  static const String mikanBangumiDetails = 'mikan://bangumi-details';

  /// 'mikan-home'
  ///
  /// [name] : 'mikan://home'
  ///
  /// [routeName] : 'mikan-home'
  static const String mikanHome = 'mikan://home';

  /// 'mikan-login'
  ///
  /// [name] : 'mikan://login'
  ///
  /// [routeName] : 'mikan-login'
  static const String mikanLogin = 'mikan://login';

  /// 'mikan-splash'
  ///
  /// [name] : 'mikan://splash'
  ///
  /// [routeName] : 'mikan-splash'
  static const String mikanSplash = 'mikan://splash';
}
