name: Build Windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
    tags-ignore:
      - v**
  workflow_dispatch:

jobs:
  build:
    name: Release build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Build windows
        run: |
          Copy-Item -Path pubspec.yaml -Destination assets -Force
          flutter config --enable-windows-desktop
          flutter build windows --release --no-tree-shake-icons
          dir build/windows/runner/Release
          Compress-Archive -Path build/windows/runner/Release/* windows-win32-release.zip -Force
      - name: Release build
        run: |
          dart scripts/github.dart --token=${{ secrets.ACTION_TOKEN }} --fun=release --artifacts=*-release.zip
